#!/usr/bin/env python3
"""Optional companion visualizations for Phase 1 zonal analysis."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render publication-quality zonal analysis figures")
    parser.add_argument(
        "--metrics-json",
        type=Path,
        default=Path("runs/zonal_analysis/zone_metrics.json"),
        help="Path to zone metrics JSON generated by zonal_map_analysis.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("runs/zonal_analysis"),
        help="Output folder for generated figures",
    )
    return parser.parse_args()


def load_rows(metrics_json: Path) -> list[dict]:
    if not metrics_json.exists():
        raise FileNotFoundError(f"Missing metrics file: {metrics_json}")
    return json.loads(metrics_json.read_text(encoding="utf-8"))


def plot_map_bars(rows: list[dict], out: Path) -> None:
    zones = [r["zone"] for r in rows]
    map50 = [r["map50"] for r in rows]
    map5095 = [r["map50_95"] for r in rows]

    x = np.arange(len(zones))
    width = 0.35

    fig, ax = plt.subplots(figsize=(7.5, 4.8))
    ax.bar(x - width / 2, map50, width, label="mAP@50")
    ax.bar(x + width / 2, map5095, width, label="mAP@50-95")
    ax.set_xticks(x)
    ax.set_xticklabels([z.capitalize() for z in zones])
    ax.set_ylim(0, 1)
    ax.set_ylabel("Score")
    ax.set_title("Fisheye OBB Performance by Radial Zone")
    ax.grid(axis="y", alpha=0.2)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out / "zone_map_bars_publication.png", dpi=220)
    plt.close(fig)


def plot_polar_density(rows: list[dict], out: Path) -> None:
    zones = [r["zone"] for r in rows]
    counts = np.array([r["gt_count"] for r in rows], dtype=np.float32)
    if counts.max() > 0:
        counts = counts / counts.max()

    theta = np.linspace(0, 2 * np.pi, len(zones), endpoint=False)
    width = np.full_like(theta, 2 * np.pi / len(zones))

    fig = plt.figure(figsize=(6, 6))
    ax = fig.add_subplot(111, projection="polar")
    ax.bar(theta, counts, width=width, alpha=0.8)
    ax.set_xticks(theta)
    ax.set_xticklabels([z.capitalize() for z in zones])
    ax.set_yticklabels([])
    ax.set_title("Normalized GT Density by Zone")
    fig.tight_layout()
    fig.savefig(out / "zone_polar_density_publication.png", dpi=220)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    rows = load_rows(args.metrics_json)
    plot_map_bars(rows, args.output)
    plot_polar_density(rows, args.output)
    print(f"Saved visualization assets to: {args.output}")


if __name__ == "__main__":
    main()
