
train: [
  "dataset/train",
  "dataset/train/labels",
]
val: [
  "dataset/val",
  "dataset/val/labels",
]


names:
  - 0 - 1 - 2 - 3 - 4 - 5 - 6 - 7 - 8 - 9
  - A - B - C - D - E - F - G - H - J - K - L - M - N - P - R - S - T - U - V - X - Y
